### ISSUE TITLE
esp32

### ISSUE THREAD

**Issue by jschoch** [alexa/alexa-gadgets-sample-code#1]
wondering if esp32 sample code is available?

**Comment by jschoch** [comment]
btstack sample code would support more than esp32 if that is possible.

**Comment by carolinepan** [comment]
Hi jschoch, our apologies for they delay in getting back to you. We currently do not have any platform specific code in our samples other than SDP code for Cypress. However, we have passed along your suggestion to support more platforms to the team and will keep you updated on new developments. Thank you again for your feedback!

**Comment by jschoch** [comment]
I was able to get the other code to work but it is not easy to debug when I can only debug one side of the connection.  My echo device does attempt to pair but I don't think the I know enough about this low level bluetooth negotiation to trouble shoot the problems.  BLE and GATT would be a bit easier I believe. 
 Unfortunately I do not have the Cypress hardware or SDK and I can't tell what the Cypress macros are generating for SDP.

**Comment by carolinepan** [comment]
Hi Jesse D Schoch, we responded to your inquiry on the dev form. Hope that provides some reference / help: https://forums.developer.amazon.com/questions/188914/looking-for-help-setting-up-the-sdp-records-for-bt.html?childToView=193065#answer-193065

**Comment by jschoch** [comment]
somone has some esp32 sample code here: https://github.com/volkhin/nixie-timer

**Comment by SevenEggs** [comment]
Hello, can you run the sample code and match it with Alexa successfully? https：//github.com/volkhin/nixie-timer
